//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debit_Card_Details
    {
        public Nullable<int> Account_Number { get; set; }
        public long Debit_Card_Number { get; set; }
        public System.DateTime Expiry_Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
