//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internet_Banking_Details
    {
        public Nullable<int> Account_Number { get; set; }
        public string Email_Id { get; set; }
        public string login_password { get; set; }
        public string transaction_password { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<int> failed_attempts { get; set; }
        public Nullable<System.DateTime> locked_time { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
