//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public int Payee_Id { get; set; }
        public Nullable<int> From_Account { get; set; }
        public Nullable<int> To_Account { get; set; }
        public string Beneficiary_Name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string Nickname { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
