//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectedAccount
    {
        public int Service_Reference_Number { get; set; }
        public string Email_Id { get; set; }
        public Nullable<System.DateTime> rejected_at { get; set; }
        public string remarks { get; set; }
    }
}
