//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMessage
    {
        public int Id { get; set; }
        public string UserEmail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime SentAt { get; set; }
        public string AdminReply { get; set; }
        public Nullable<System.DateTime> RepliedAt { get; set; }
        public string Status { get; set; }
    }
}
