//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Details
    {
        public int Transaction_Id { get; set; }
        public Nullable<int> From_Account { get; set; }
        public Nullable<int> To_Account { get; set; }
        public string Transaction_Mode { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Remarks { get; set; }
    }
}
